# -*- coding: utf-8 -*-
"""[ProtonX] TensorFlow Example 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GGsj_bGlmd5OrmRbVYwvC1VaR2j2R4an

# Đề thi mẫu chứng chỉ TensorFlow - Dạng bài 01

```
ProtonX - TensorFlow Class
```
Giới thiệu về chứng chỉ - https://www.tensorflow.org/certificate

> Chú ý: đọc kỹ các nội dung trong Handle Notebook trong liên kết trên.

---

### Hướng dẫn làm bài

Đọc kỹ File `Tensorflow Exam - Tips` trên hệ thống Google.

*Một số yêu cầu:
- Sử dụng TensorFlow 2.x trở lên.
- Không có tập validation nên train tầm 500 - 1000 epochs để đảm bảo đạt độ chính xác.
- Chạy lại toàn bộ File này trước khi ấn nộp bài.

### Phần lập trình
"""

# Import thư viện cần thiết
import tensorflow as tf
import numpy as np

# Dữ liệu
xs = [2, 7, 9, 3, 10, 6, 1, 8]
ys = [13, 35, 41, 19, 45, 28, 10, 55]

xs = np.array(xs, dtype = float)
ys = np.array(ys, dtype = float)

min_feature, max_feature = min(xs), max(xs)
feature = (xs - min_feature) / (max_feature - min_feature)

xs

feature

model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(1, input_shape = [1])
])

model.compile(optimizer = 'sgd', loss = 'mean_squared_error')

model.fit(xs, ys, epochs = 750, verbose = 1)

# Lưu Model và nộp
model.save("mymodel.h5")

model.predict([3])

